'''
Pedro Ramirez
Class: CS 521 - Spring 1
Date: 3/3/2023
Final Project
Description:
User class to create an account.
It will inherit from the Bank class.
It contains the attributes and methods necessary to create
and validate a new account.
it uses the uuid module to generate a unique account number.
'''

from bank import Bank
import uuid


class User(Bank):
    '''
    User class to create and validate a new account.
    It will inherit from the Bank class.
    In addition to the id generated by the uuid module,
    it contains a class attribute to be appended to the account number.
    '''

    __incremental_id = 0

    def __init__(self, name='', age='', email='', username='', password=''):
        super().__init__()
        self.holder_name = name
        self.age = age
        self.email = email
        self.username = username
        self.password = password
        User.__incremental_id += 1

    def create_account(self) -> None:
        '''Create a new account and assign it to the attributes.'''
        name = self.add_name()
        last = self.add_last()
        self.balance = self.initial_amount()
        self.holder_name = self.__add__(name, last)
        self.age = self.add_age()
        self.email = self.add_email()
        self.username = self.add_username()
        self.password = self.add_password()
        self.account_number = uuid.uuid4().hex[:8] + str(User.__incremental_id)

    def save_account(self) -> dict:
        '''
        return a dictionary with the account information
        to be saved using sqlite3.
        '''
        return {
            'name': self.holder_name,
            'balance': self.balance,
            'account': self.account_number,
            'age': self.age,
            'email': self.email,
            'username': self.username,
            'password': self.password,
        }

    def add_name(self) -> str:
        '''Adds and validate the name input.'''
        while True:
            name = input('Enter your name: ')
            try:
                for char in name:
                    if not char.isalpha():
                        raise ValueError
            except ValueError:
                print('Error', 'Name must contain only letters')

            else:
                break
        return name

    def add_last(self) -> str:
        '''Adds and validate the last name input.'''
        while True:
            last = input('Enter your last name: ')
            try:
                for char in last:
                    if not char.isalpha():
                        raise ValueError
            except ValueError:
                print('Error', 'Name must contain only letters')
            else:
                break
        return last

    def initial_amount(self) -> float:
        '''Adds and validate the initial amount input.'''
        while True:
            amount = input('Enter initial amount: ')
            try:
                if not float(amount):
                    raise ValueError
                if float(amount) < 0:
                    raise TypeError
            except ValueError:
                print('Error', 'Amount must be a number')
            except TypeError:
                print('Error', 'Amount must be greater than 0')
            else:
                break
        return float(amount)

    def add_age(self) -> int:
        '''Adds and validate the age input.'''
        while True:
            age = input('Enter your age: ')
            try:
                if not int(age):
                    raise ValueError
                if int(age) < 18:
                    raise TypeError()
            except ValueError:
                print('Error', 'Age must be a number')
            except TypeError:
                print(
                    'Error',
                    'You must be at least 18 years old to open an account',
                )
            else:
                break
        return int(age)

    def add_email(self) -> str:
        '''Adds and validate the email input.'''
        while True:
            email = input('Enter your email: ')
            try:
                if self.__validate_email(email) is False:
                    raise ValueError
            except ValueError:
                print('Error', 'Enter a valid email')
            else:
                break
        return email

    def add_username(self) -> str:
        '''Adds and validate the username input.'''
        while True:
            username = input('Enter your username: ')
            try:
                if len(username) < 6:
                    raise ValueError
            except ValueError:
                print('Error', 'Username must be at least 6 characters long')
            else:
                break
        return username

    def add_password(self) -> None:
        '''Adds and validate the password input.'''
        while True:
            password = input('Enter your password: ')
            try:
                if len(password) < 8:
                    raise ValueError
            except ValueError:
                print('Error', 'Password must be at least 8 characters long')
            else:
                break
        return password

    def __add__(self, name, last):
        '''Concatenate the name and last name.'''
        return name + ' ' + last

    def __validate_email(self, email) -> bool:
        '''Validate the email using regex.'''
        import re

        regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
        if re.match(regex, email):
            return True
        else:
            return False

    def __repr__(self) -> str:
        '''Return the account information.'''
        return f'\
     Your account information:\n\
     Account number: {self.account_number}\n\
     Name: {self.holder_name}\n\
     Balance: {self.balance}\n\
     Age: {self.age}\n\
     Email: {self.email}\n\
     Username: {self.username}\n\
     Password: {self.password}\n'
